application: interact-data-analysis
version: test
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /.*
  script: data_analysis.application

libraries:
- name: jinja2
  version: latest

- name: numpy
  version: latest

